
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: furima_39216-development

test:
  <<: *default
  database: furima_39216-test

#切り替え
production:
  <<: *default
  database: furima-39216-production
  username: furima-39216
  password: <%= ENV['FURIMA-39216_DATABASE_PASSWORD'] %>



default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima-39216_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima-39216_test

production:
  <<: *default
  adapter: mysql2
  database: furima-39216_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock